export const completedTrip = [
  {
    id: 1,
    stop_order: 0,
    stop_name: "texas State Capital",
    trip_id: 2,
    thumbnail_url: "https://via.placeholder.com/140x100",
    time_stamp: null,
    greater_location: "Austin Texas",
    google_place_id: "ChIJ_5CoRebFxokR08ApAyF2KIs",
  },
  {
    id: 1,
    stop_order: 1,
    stop_name: "The Ritz-Carlton, Philadelphia",
    trip_id: 2,
    thumbnail_url: "https://via.placeholder.com/140x100",
    time_stamp: null,
    greater_location: "Philadelphia",
    google_place_id: "ChIJv51-sC_GxokR6fV5EFtVIyc",
  },
  {
    id: 1,
    stop_order: 2,
    stop_name: "Motel 6",
    trip_id: 2,
    thumbnail_url: "https://via.placeholder.com/140x100",
    time_stamp: null,
    greater_location: "La La Land",
    google_place_id: "ChIJR7HjD-zFxokRLbpFP7Ixn1I",
  },
  {
    id: 1,
    stop_order: 3,
    stop_name: "Fairfield Inn & Suites by Marriott Pottstown Limerick",
    trip_id: 2,
    thumbnail_url: "https://via.placeholder.com/140x100",
    time_stamp: null,
    greater_location: "Down the Rabbit Hole",
    google_place_id: "ChIJcyi5fSzGxokRE4Z2-OK6ogE",
  },
  {
    id: 1,
    stop_order: 4,
    stop_name: "The Philip and Muriel Berman Museum Of Art",
    trip_id: 2,
    thumbnail_url: "https://via.placeholder.com/140x100",
    time_stamp: null,
    greater_location: "Down the Rabbit Hole",
    google_place_id: "ChIJMd064KnHxokRCTcp1DYABfQ",
  },
  {
    id: 1,
    stop_order: 5,
    stop_name: "Dennys",
    trip_id: 2,
    thumbnail_url: "https://via.placeholder.com/140x100",
    time_stamp: null,
    greater_location: "Down the Rabbit Hole",
    google_place_id: "ChIJxz_iGfS4xokRgo1A_0OIjz0",
  },
  {
    id: 1,
    stop_order: 6,
    stop_name: "Outback",
    trip_id: 2,
    thumbnail_url: "https://via.placeholder.com/140x100",
    time_stamp: null,
    greater_location: "Down the Rabbit Hole",
    google_place_id: "ChIJKTDM4i_GxokRhTLAjRMs9sw",
  },
];
